n= -10:10;
x= exp((-0.1+0.3j)*n);
magnitude= abs(x);
phase_angle_degree= angle(x)*(180/pi);
real_part= real(x);
imaginary_part= imag(x);
subplot(2,2,1); stem(n,magnitude); title('Magnitude');xlabel('n'); ylabel('Magnitude');
subplot(2,2,2); stem(n,phase_angle_degree); title('phase angle degree');xlabel('n'); ylabel('Phase');
subplot(2,2,3); stem(n,real_part); title('Real part');xlabel('n'); ylabel('Real part');
subplot(2,2,4); stem(n,imaginary_part); title('Imaginary part');xlabel('n'); ylabel('Imaginary part');
